development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: piratenportal_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: piratenportal_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: postgresql
  encoding: unicode
  database: piratenportal_production
  pool: 5
  username: piratenportal
  password:
